#!/usr/bin/env python3
from pathlib import Path
root=Path(__file__).resolve().parent.parent;out=root/'site/homepanel-mr';out.mkdir(parents=True,exist_ok=True)
email='hohiep102@gmail.com';base='https://homepanel-mr.pages.dev'
css='''*{box-sizing:border-box}body{margin:0;background:#091319;color:#edf5f0;font:18px/1.7 system-ui,-apple-system,sans-serif}a{color:#91e6c2;text-underline-offset:4px}header,footer,main{max-width:1000px;margin:auto;padding:28px}header{display:flex;justify-content:space-between;border-bottom:1px solid #2b3b45;gap:25px}nav{display:flex;gap:24px}main{padding-top:64px;padding-bottom:90px}h1{font-size:clamp(38px,7vw,72px);line-height:1.05;letter-spacing:-2px}h2{font-size:28px;margin-top:48px}p,li{color:#b5c7cb}strong{color:#edf5f0}.intro{font-size:22px;max-width:760px}.tag{color:#91e6c2;font-size:12px;letter-spacing:3px;text-transform:uppercase}.summary{border-left:3px solid #91e6c2;background:#14232c;padding:22px 28px;margin:36px 0}.brand{font-weight:800;letter-spacing:2px;text-decoration:none;color:#edf5f0}.meta,footer{font-size:14px;color:#9caeba}footer{border-top:1px solid #2b3b45}.button{display:inline-block;padding:12px 20px;background:#91e6c2;color:#091319;border-radius:8px;text-decoration:none;font-weight:700}@media(max-width:620px){header{flex-direction:column}main{padding-top:34px}nav{gap:18px;font-size:15px}}'''
(out/'style.css').write_text(css)
privacy='''<div class="tag">Your information and your choices</div><h1>Privacy policy</h1><p class="meta">HomePanel MR · Effective 4 October 2026<br>Publisher and operator: hohiep102<br>Privacy contact: <a href="mailto:hohiep102@gmail.com">hohiep102@gmail.com</a></p><div class="summary"><strong>Your Home Assistant connection and room placements stay on your headset.</strong><p>HomePanel MR has no developer-operated account, analytics service, advertising service or cloud relay. It communicates directly with the Home Assistant server you select. Meta platform services, the public website and support email have separate processing described below.</p></div>
<h2>1. Home Assistant connection and device information</h2><p>The app processes your Home Assistant server address, authentication tokens, device and entity names, areas, supported actions and current states so that it can display and control your devices. Commands you choose are sent to your selected Home Assistant server. We do not receive a copy on a developer server.</p><p>Browser sign-in takes place on your Home Assistant server. HomePanel MR receives an authorization result and exchanges it for tokens. When you choose to remember the connection, tokens are encrypted in private app storage using an Android Keystore key. The server address and app preferences are stored locally. If you do not remember the connection, credentials are kept for the active session. Device states may reveal information about your home; your Home Assistant server and its integrations govern their own storage and onward processing.</p><p>The app can discover Home Assistant servers on your local network when you use discovery. HTTPS certificate validation is enabled. If you choose a local HTTP server, traffic to that server is not encrypted in transit; use it only on a trusted private network.</p>
<h2>2. Room data, hand input and passthrough</h2><p>With permission, HomePanel MR uses the room model and spatial anchors provided by Meta's operating system to place device controls. The app saves room and anchor identifiers, relative positions, orientation, sizes, device/entity identifiers and your labels in its private local storage. It processes head, hand and controller input to aim and interact. The app does not record motion histories, access raw camera images, record room video or upload room models or placements to a developer server.</p><p>Passthrough, room setup, tracking and system-managed spatial data are provided by Meta and subject to Meta's policies and device privacy controls. Denying spatial-data permission prevents room placement; you can still use the ordinary device-control window.</p>
<h2>3. Meta platform services</h2><p>The Store build uses Meta's Platform SDK to verify that your Meta account has access to the app. HomePanel MR does not request your profile, friends list or a Meta user ID. Meta may process account, purchase, device and diagnostic information under <a href="https://www.meta.com/legal/privacy-policy/">Meta's Privacy Policy</a>. The app writes limited technical status messages to local Android system logs for troubleshooting; it does not intentionally log passwords, tokens, device names or spatial coordinates.</p>
<h2>4. Support messages</h2><p>If you contact hohiep102@gmail.com, we receive the email address, message and attachments you send. We use them to respond and troubleshoot. The mailbox uses Google's Gmail service. We keep correspondence only as needed to handle the request or meet applicable legal obligations. Do not send passwords, Home Assistant tokens or unnecessary private room images. You may request access, correction or deletion using the same address. We do not sell support messages or use them for advertising.</p>
<h2>5. This website</h2><p>This static website is hosted by Cloudflare Pages. Cloudflare may process request information such as IP address, requested page and time to deliver and protect the site; see <a href="https://www.cloudflare.com/privacypolicy/">Cloudflare's Privacy Policy</a>. These pages contain no added analytics, advertising trackers, tracking cookies, embedded third-party video, accounts or contact forms. Following an external link uses that service's privacy practices. Hosting and email providers may process information outside your country.</p>
<h2>6. Your controls and deletion</h2><ul><li>Use Disconnect and forget in the Connection page to remove saved connection credentials. Browser-issued refresh tokens are revoked when the server is reachable; you can also revoke tokens in your Home Assistant profile. Long-lived tokens must be revoked in Home Assistant.</li><li>Remove individual placements from the Placed page. Forgotten connections do not automatically erase saved placements.</li><li>Clear app storage or uninstall to remove local credentials, placements and preferences. Android backup and app-data transfer are disabled. We cannot restore local data.</li><li>Manage system room scans, permissions and Meta account or purchase records through Meta's settings. Removing the app does not delete your Home Assistant server data or Meta records.</li><li>For support-email information or privacy rights, contact hohiep102@gmail.com. We may need enough information to verify a request belongs to you. You may have additional rights under applicable privacy laws, including contacting your data-protection authority.</li></ul>
<h2>7. Children and changes</h2><p>The app does not ask for names, birthdays or contact details. Availability for account age groups is governed by Meta and the Store rating. A parent or guardian may contact us about information a child sent to support. We will update this page and its date when the app's data handling changes. This policy applies to HomePanel MR and this website.</p>'''
support='''<div class="tag">HomePanel MR support</div><h1>Get your room connected.</h1><p class="intro">HomePanel MR is an independent mixed reality client for Home Assistant on Meta Quest 3 and Quest 3S.</p><p><a class="button" href="mailto:hohiep102@gmail.com?subject=HomePanel%20MR%20support">Email support</a></p><h2>What you need</h2><p>A working Home Assistant server, an account with access to your devices, compatible configured devices and a network connection from the headset to the server. Home Assistant and smart-home hardware are not included.</p><h2>Try the demo</h2><p>Select Explore demo on the welcome screen. Sample lights, climate and other devices can be explored without a Home Assistant account. Demo actions do not operate real devices.</p><h2>Connect your home</h2><p>Open Connection, discover your server or enter its address, then use browser sign-in. Token sign-in is also available. Check that the headset can reach the server. Use HTTPS where possible; use HTTP only on a trusted private network. Never send your tokens to support.</p><h2>Find and place a device</h2><p>Browse Rooms or Devices. Everyday hides configuration and diagnostic entities; All devices shows the full catalog. Devices with several switch channels list each channel separately. Select the intended channel and choose Place in room.</p><p>Complete Meta room setup, grant spatial-data permission, aim the frame at the object, adjust its size, freeze it and save. Return to the same mapped room to resolve saved placements. Changing or deleting the system room scan may require placing controls again.</p><h2>Use small controls</h2><p>Look toward a saved device briefly to reveal its action icons. Point and pinch or directly touch a button. Looking alone never sends a device command. Look away from both the device and the icons to hide them. The more button opens detailed controls.</p><h2>Access or connection problems</h2><p>For a Store ownership error, use the Meta account that purchased the app or has access to the test channel, then retry. A grey control can mean an unavailable device or unsupported action. Reconnect your Home Assistant server and check the device there.</p><h2>Report an issue</h2><p>Include the app version, headset model, affected Home Assistant entity domain and steps to reproduce. Share a screenshot only if it contains no private information. Do not include credentials or access tokens.</p>'''
home='''<div class="tag">Mixed reality · Home Assistant</div><h1>Your smart home.<br>Right in front of you.</h1><p class="intro">Put small controls beside the devices in your room. Look, select an action with your hands, then look away to keep your view clear.</p><div class="summary"><strong>HomePanel MR for Meta Quest 3 and Quest 3S</strong><p>Lights, switch channels, climate, fans and covers. English and Vietnamese. Built-in demo. Preparing for Meta Horizon Store release.</p></div><p>Real device control requires your own working Home Assistant server, compatible devices and network access. Available actions depend on your integrations. Room placement uses Meta room setup and spatial-data permission.</p><p><a class="button" href="support/">Getting started</a></p><p class="meta">An independent app by hohiep102. Not affiliated with the Open Home Foundation or Meta.</p>'''
def page(title,body,section=''):
 prefix='/'
 return f'<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{title} | HomePanel MR</title><meta name="description" content="HomePanel MR mixed reality controls for Home Assistant, privacy and support."><link rel="stylesheet" href="{prefix}style.css"><link rel="canonical" href="{base}/{section+"/" if section else ""}"></head><body><header><a class="brand" href="{prefix}">HOME / PANEL MR</a><nav><a href="{prefix}support/">Support</a><a href="{prefix}privacy/">Privacy</a></nav></header><main>{body}</main><footer>© 2026 hohiep102 · <a href="mailto:{email}">{email}</a> · <a href="{prefix}privacy/">Privacy</a></footer></body></html>'
for folder,title,body in [('', 'Home',home),('privacy','Privacy policy',privacy),('support','Support',support)]:
 p=out/folder;p.mkdir(exist_ok=True);(p/'index.html').write_text(page(title,body,folder))
(out/'404.html').write_text(page('Page not found','<h1>Page not found</h1><p>Visit the <a href="/">HomePanel MR home page</a> or <a href="/support/">get support</a>.').replace(f'<link rel="canonical" href="{base}/">','<meta name="robots" content="noindex">'))
(out/'_headers').write_text("""/*
  Content-Security-Policy: default-src 'none'; style-src 'self'; img-src 'self'; base-uri 'none'; form-action 'none'; frame-ancestors 'none'
  X-Frame-Options: DENY
  X-Content-Type-Options: nosniff
  Referrer-Policy: no-referrer
  Permissions-Policy: camera=(), microphone=(), geolocation=()
  Strict-Transport-Security: max-age=31536000
  Cache-Control: public, max-age=300
""")
print(out)
